name: Fernet REST Service CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  test-and-build:

    runs-on: ubuntu-latest
env:
  FERNET_SECRET: ${{ secrets.FERNET_SECRET }}
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Run Jest Tests
        run: npm test

      - name: Build Docker Image
        run: docker build -t fernet-rest-service .